version: '3.8'

services:
  django-app:
    build: .
    volumes:
      - ./app:/app
      - ../deepserializers:/deepserializers
      - ../tests:/tests
      - ../:/all
    ports:
      - "8000:8000"
    restart: unless-stopped