version: '3.8'

services:
  django-app:
    build: .
    volumes:
      - ./app:/app
      - ../:/deepserializers
      - /tmp/python:/usr/local/bin/python3
    ports:
      - "8000:8000"
    restart: unless-stopped