@startuml deep_viewset_conception

legend top left
== Overview of deepviewset conception ==
This file is an overview of viewet conception in the module that not a real conception.

CRUD - Create, Read, Update, Delete
Deep - Mean that the CRUD operation is able to be done in depth.
endlegend

class ModelViewSet {
    + create
    + list
    + retrieve
    + update
    + partial_update
    + destroy
}

class DeepViewSet {
    + Needed method for the deep operation of the module
}

class ReadOnlyModelViewSet {
    + list
    + retrieve
}

class ReadOnlyModelDeepViewSet {
    + list + Deep
    + retrieve + Deep
}

class ModelDeepViewSet {
    + create + Deep
    + list + Deep
    + retrieve + Deep
    + update + Deep
    + partial_update
    + destroy
}

class SecureModelDeepViewSet {
    + create
    + list + Deep
    + retrieve + Deep
    + update
    + partial_update
    + destroy
}

SecureModelDeepViewSet <|-- ModelViewSet
SecureModelDeepViewSet <|-- ReadOnlyModelDeepViewSet

ModelDeepViewSet <|-- ReadOnlyModelDeepViewSet
ModelDeepViewSet <|-- ModelViewSet

ReadOnlyModelDeepViewSet <|-- ReadOnlyModelViewSet
ReadOnlyModelDeepViewSet <|-- DeepViewSet

@enduml
